### ISSUE TITLE
better mobile menu

### ISSUE THREAD

**Issue by Vandivier** [Vandivier/arias-tale-rpg#97]
<img width="586" alt="image" src="https://github.com/Vandivier/arias-tale-rpg/assets/5559355/c30026fb-bd1e-44eb-97a7-885f914d7099">

it takes up lots of real estate now that it's grown. let's have a one-line row where "Aria's Tale" is in the top-left and it will take you to home, or "Menu" is in the top right and it will expand to show the other options (expand, not route change, so players don't lose game state if they expand and collapse mid-game)

**Comment by Vishalvirdi** [comment]
Hi @Vandivier Can u assign this issue to me. I would love to contribute.
